version: '3'

services:
  php:
    build:
      context: ./docker/php
    volumes:
      - './src:/var/www/html'
  mysql:
    image: mysql:8.0.22
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: currency_converter
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - './docker/volume/mysql:/var/lib/mysql'
  nginx:
    image: nginx:1.18
    ports:
      - "8084:80"
    volumes:
      - './docker/nginx/conf.d:/etc/nginx/conf.d'
      - "./src:/var/www/html"
    depends_on:
      - mysql


